name: CI/CD Pipeline

on:
  pull_request:        
    branches: [main]
  push:                
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Validate
        run: cd terraform && terraform validate

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Docker Build Test
        run: docker build -t test-frontend ./app-deployment/app/frontend && docker build -t test-backend ./app-deployment/app/backend

      - name: Install kubeval
        run: |
           curl -sLO https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
           tar xf kubeval-linux-amd64.tar.gz
           sudo mv kubeval /usr/local/bin/

      - name: Validate Kubernetes manifests (syntax only)
        run: kubeval --ignore-missing-schemas app-deployment/k8s/*.yml

  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Plan
        run: cd terraform && terraform plan

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build & Push
        run: |
          docker build -t vaishnavi0706/frontend:latest ./app-deployment/app/frontend
          docker push vaishnavi0706/frontend:latest
          docker build -t vaishnavi0706/backend:latest ./pp-deployment/app/backend
          docker push vaishnavi0706/backend:latest

      -  name: Setup kubeconfig
         run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config


      - name: Kubernetes Deploy
        run: kubectl apply -f ./app-deployment/k8s/

      - name: Rollout Verification
        run: kubectl rollout status deployment/frontend && kubectl rollout status deployment/backend

      - name: Smoke Test API
        run: curl -f http://4.187.159.100/api/health
