apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-servicemonitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: backend       
  namespaceSelector:
    matchNames:
      - app             
  endpoints:
    - port: http            
      targetPort: 5000      
      path: /metrics       
      interval: 15s         
